version: "3.7"
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/main_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=user
      - spring.datasource.password=pass
    depends_on:
      - db

  db:
    image: "mysql:8.0"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: main_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass